### ISSUE TITLE
hey im trying to install a pcbs mod (pc building simuator) then i get this

### ISSUE THREAD

**Issue by dogefan99991** [synogen/unitypatcher#4]
" java.nio.file.NoSuchFileException: ..\PCBS_Data\sharedassets1.assets
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at org.synogen.unitypatcher.AssetFile.parse(AssetFile.java:50)
        at org.synogen.unitypatcher.App.main(App.java:38)
--------------

**Comment by dogefan99991** [comment]
someone please help
